### ISSUE TITLE
Test Case Failure Registration 2.1.6

### ISSUE THREAD

**Issue by Aayushman136** [aakashbanerjee98/SWE-Lab-Project-eMeds-#2]
The Phone number gets accepted even if the number is not 10 digit

**Comment by aakashbanerjee98** [comment]
Phone number checker has been added invalid phone number will not  be accepted. 
Changes has been made in [Registration Ui](https://github.com/aakashbanerjee98/SWE-Lab-Project-eMeds-/blob/00c8382240009a51c41d4037224c2e3592710eac/src/RegistrationUi.java#L182)
