### ISSUE TITLE
Test Case Failure  Registration 2.2.7

### ISSUE THREAD

**Issue by AdrishGanguly** [aakashbanerjee98/SWE-Lab-Project-eMeds-#3]
Not checking for correct gender . Accepting any thing including None .

**Comment by aakashbanerjee98** [comment]
Gender checking has been added only Female or Male gender can be accepted.
Changes has been made to [Registration UI](https://github.com/aakashbanerjee98/SWE-Lab-Project-eMeds-/blob/00c8382240009a51c41d4037224c2e3592710eac/src/RegistrationUi.java#L187)
