### ISSUE TITLE
Test Case Registration 2.1.8

### ISSUE THREAD

**Issue by AdrishGanguly** [aakashbanerjee98/SWE-Lab-Project-eMeds-#4]
The age was taking negative values .

**Comment by aakashbanerjee98** [comment]
Age verification has been added. As age can be only positive integers. So it will take only positive integers.
Changes has been added in [Registration Ui](https://github.com/aakashbanerjee98/SWE-Lab-Project-eMeds-/blob/00c8382240009a51c41d4037224c2e3592710eac/src/RegistrationUi.java#L192)
