### ISSUE TITLE
2.4.4 Upload Medical Records

### ISSUE THREAD

**Issue by Aayushman136** [aakashbanerjee98/SWE-Lab-Project-eMeds-#5]
The Selected path was not selecting

**Comment by Aayushman136** [comment]
The issues has been solved. the selected path is working

**Comment by Aayushman136** [comment]
The issue has been solved. The selected path is working

**Comment by aakashbanerjee98** [comment]
Changes were made in [UploadMedicalRecords](https://github.com/aakashbanerjee98/SWE-Lab-Project-eMeds-/blob/e5e2fcfeb7f8303486f8754491e7e56c9bb16480/src/UploadMedicalRecords.java#L268)
